### ISSUE TITLE
iam.gserviceaccount.com does not have storage.objects.get access to the Google Cloud Storage object.

### ISSUE THREAD

**Issue by lucqui** [alehechka/medium-react-gcr#1]
So looks like when I have set this up everything is working until the `Build and Deploy` step where I'm getting this error:
```iam.gserviceaccount.com does not have storage.objects.get access to the Google Cloud Storage object.```. 

I have added all Roles involving Cloud Storage so kind of confused why that would be an issue. I tried to then go through the manual process of adding the docker image to the registry but it only appears to add it locally and doesn't actually appear in the cloud for some reason (no error on the command line). I can see it when I list it from the command line locally but not in the online console. Will keep looking but it's very confusing all and all.

**Comment by lucqui** [comment]
I also wouldn't be surprised if all troubles here are stemming from new bugs coming from the new architecture on mac... That seems to be the majority of my issues lately TBH.

**Comment by alehechka** [comment]
Hey sorry for the late response, just now saw this. It has been a while since I wrote that article so GCP permissions may have changed. Make sure you have all the [permissions](https://medium.com/swlh/deploying-a-react-app-to-google-cloud-run-with-github-actions-ae24ac6cb85a#ebbc) though. Looks like `Cloud Build Editor` and `Cloud Build Service Account` are what allow you to deploy via GitHub Actions. 

As for the manual deployment, make sure to tag and push the docker image correctly, steps found [here](https://medium.com/swlh/deploying-a-react-app-to-google-cloud-run-with-github-actions-ae24ac6cb85a#a6ae).
